var dummyData = {
// info page ( multi-menu )
	"About company ?":"<div class=\"col-md-12 animated fadeIn test-multi-menu\"><h3>Example page info.</h3><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere similique necessitatibus distinctio consequuntur obcaecati maiores rerum autem libero quae quasi fugiat, corrupti, ipsam voluptates accusamus, porro officia quod. Labore, tempora.</p><div class=\"col-md-12 test-block-1\"><ul><li class=\"col-md-3\"><i class=\"material-icons\">&#xE885;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90D;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE88F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li></ul><div class=\"col-md-12 test-multi-menu-2 text-center\"><img src=\"./../../../images/dribbble.gif\"/></div></div></div>",

	"About portfolio ?":"<div class=\"col-md-12 info-small\"><div class=\"col-md-12 info-small-text\"><div class=\"col-md-3\"><i class=\"material-icons\">&#xE8F8;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE854;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit <a href=\"#\">officiis minus!</a> Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE87E;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\"><i class=\"material-icons\">&#xE90D;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\">\<i class=\"material-icons\">&#xE912;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div></div>",

	"About services ?":"<div class=\"col-md-12 info-small\"><div class=\"col-md-12 info-small-text\"><div class=\"col-md-3\"><i class=\"material-icons\">&#xE8F8;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE854;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit <a href=\"#\">officiis minus!</a> Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE87E;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\"><i class=\"material-icons\">&#xE90D;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\">\<i class=\"material-icons\">&#xE912;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div></div>",

	"About blog ?":"<div class=\"col-md-12 animated fadeIn test-multi-menu\"><h3>Example page info.</h3><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere similique necessitatibus distinctio consequuntur obcaecati maiores rerum autem libero quae quasi fugiat, corrupti, ipsam voluptates accusamus, porro officia quod. Labore, tempora.</p><div class=\"col-md-12 test-block-1\"><ul><li class=\"col-md-3\"><i class=\"material-icons\">&#xE885;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90D;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE88F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li></ul></div></div>",

	"Who we are ?":"<div class=\"col-md-12 info-small\"><div class=\"col-md-12 info-small-text\"><div class=\"col-md-3\"><i class=\"material-icons\">&#xE8F8;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE854;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit <a href=\"#\">officiis minus!</a> Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE87E;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\"><i class=\"material-icons\">&#xE90D;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\">\<i class=\"material-icons\">&#xE912;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div></div>",

	"What we do ?":"<div class=\"col-md-12 animated fadeIn test-multi-menu\"><h3>Example page info.</h3><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere similique necessitatibus distinctio consequuntur obcaecati maiores rerum autem libero quae quasi fugiat, corrupti, ipsam voluptates accusamus, porro officia quod. Labore, tempora.</p><div class=\"col-md-12 test-block-1\"><ul><li class=\"col-md-3\"><i class=\"material-icons\">&#xE885;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90D;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE88F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li></ul></div></div>",

	"Our plans ?":"<div class=\"col-md-12 info-small\"><div class=\"col-md-12 info-small-text\"><div class=\"col-md-3\"><i class=\"material-icons\">&#xE8F8;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE854;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit <a href=\"#\">officiis minus!</a> Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE87E;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\"><i class=\"material-icons\">&#xE90D;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\">\<i class=\"material-icons\">&#xE912;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div></div>",

	"What we love ?":"<div class=\"col-md-12 animated fadeIn test-multi-menu\"><h3>Example page info.</h3><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere similique necessitatibus distinctio consequuntur obcaecati maiores rerum autem libero quae quasi fugiat, corrupti, ipsam voluptates accusamus, porro officia quod. Labore, tempora.</p><div class=\"col-md-12 test-block-1\"><ul><li class=\"col-md-3\"><i class=\"material-icons\">&#xE885;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90D;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE88F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li></ul></div></div>",

	"Who am I ?":"<div class=\"col-md-12 info-small\"><div class=\"col-md-12 info-small-text\"><div class=\"col-md-3\"><i class=\"material-icons\">&#xE8F8;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE854;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit <a href=\"#\">officiis minus!</a> Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div><div class=\"col-md-3\"><i class=\"material-icons\">&#xE87E;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum <a href=\"#\">similique odit</a> officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\"><i class=\"material-icons\">&#xE90D;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! Maxime voluptatem cum non, tempora vitae.</p></div><div class=\"col-md-6\">\<i class=\"material-icons\">&#xE912;</i><h5>Example name</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis repellat, tempora voluptates harum doloribus numquam, est facere suscipit, cumque eum similique odit officiis minus! <a href=\"#\">Maxime voluptatem</a> cum non, tempora vitae.</p></div></div>",

	"What I do ?":"<div class=\"col-md-12 animated fadeIn test-multi-menu\"><h3>Example page info.</h3><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere similique necessitatibus distinctio consequuntur obcaecati maiores rerum autem libero quae quasi fugiat, corrupti, ipsam voluptates accusamus, porro officia quod. Labore, tempora.</p><div class=\"col-md-12 test-block-1\"><ul><li class=\"col-md-3\"><i class=\"material-icons\">&#xE885;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE90D;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li><li class=\"col-md-3\"><i class=\"material-icons\">&#xE88F;</i><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ab mollitia tempora repellat doloremque minima a dolore perspiciatis beatae repudiandae nobis provident, modi ullam voluptas molestiae sunt, libero pariatur explicabo.</p></li></ul></div></div>",

	"What are your plans ?":"<div class=\"col-md-12 text-center\"><img src=\"./../../../images/dribbble.gif\"/></div>",

	"What I love ?":"<div class=\"col-md-12 text-center\"><img src=\"./../../../images/cymatic.gif\"/></div>",

	"How can I help ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Shipping of goods ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Payment ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Pay ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Gorant ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Return of funds ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"My philosophy ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Philosophy company ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Philosophy products ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Philosophy portfolio ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Philosophy services ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Philosophy blog ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"IT ?":"<div class=\"col-md-12 text-center\"><h4>Eample name</h4><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis esse ipsam vitae. Qui, officiis ad assumenda nemo fugiat deleniti, culpa sapiente eos quidem recusandae molestias ipsa cumque est doloremque ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus temporibus velit facilis dicta, nam, mollitia sit eos ut commodi ipsa, natus ipsum quis atque alias ex tenetur cum ducimus, consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis veritatis unde cum amet voluptatum aperiam nostrum voluptatem, voluptas, dolor obcaecati. Odio in autem repellendus placeat laudantium, quaerat animi, voluptates voluptas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, ipsum facilis in exercitationem corporis voluptatem expedita sunt molestias vel. Praesentium minima laboriosam explicabo pariatur quos hic? Est pariatur necessitatibus laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati similique commodi blanditiis necessitatibus quisquam quia, unde sit at, illo ipsam nihil reprehenderit excepturi dolor quasi nobis esse quos, voluptas velit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa officia doloribus fugit, non, aliquam saepe omnis rerum expedita, eaque modi repellat dicta architecto laudantium! Doloribus incidunt nesciunt, mollitia excepturi rem.</p></div>",

	"Design ?":").",
	"Technology ?":").",
	"Food ?":").",
	"Profit ?":").",
	"MLM system ?":").",
	"Income from sales ?":").",
	"Your people ?":").",
	"Withdrawal of funds ?":").",
	"It development ?":").",
	"PHP development ?":").",
	"Front-end ?":").",
	"Back-end":").",
	"Paid help ?":").",
	"Free help ?":").",
	"Any suggestions ?":").",
	"Not our answer ?":").",
	"Other reasons ?":").",

// portfolio page ( multi-menu )	
	"Experements ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",
	
	"WordPress ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Joomla ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Drupal ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Concrete5 ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"MODX ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Webflow ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Mura ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Moodle ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Admin ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Corporate ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Creative ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Entertainment ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Mobile ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Nonprofit ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Personal ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Retail ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Technology ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Wedding ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"HTML ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Bootstrap ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Muse ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Landing Pages ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Home ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"About us ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"About me ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Portfolio ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Shop ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Services ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Blog ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Contacts ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Sign in ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Head ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Footer ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Menu ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Post-item ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Coments-item ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Modal ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Product ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Windows ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Linux ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"OSX ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Chrome OS ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Android ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Iphone ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Windows phone ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Multi-all ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Browser ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"OS ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"SVG ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"PNG ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Icon pack ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Paterns ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Blur ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Gif ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"JPG ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Colections ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Experements ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

	"Vectors ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",
	
	"Infografics ?":"<div class=\"col-md-12 portfolio-small\"><div class=\"col-md-12 portfolio-small-item\"><ul><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li><li class=\"col-md-4\"><a href=\"#\"><div class=\"col-md-12 ex-portfolio\"></div></a></li></ul></div></div>",

// services page ( multi-menu )
	"Working with data ?":"<div class=\"col-md-12 category-services\"><h5>Working with data:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit qui iste, iusto ipsam placeat voluptas sit dolor amet, voluptatum ad, rem animi? Esse ab dolorem nemo error omnis, veniam est? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi sit, quia doloribus facere non ab, ipsa error animi. Dicta eum at architecto velit dignissimos facilis itaque dolor mollitia inventore perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio minima tempora qui molestiae asperiores cum ipsam, est ipsa soluta. Optio enim possimus, dolores vitae ipsa libero facere, totam illo fugiat!</p><ul><li class=\"col-md-4\"><a href=\"#\">Big Data ?</a></li><li class=\"col-md-4\"><a href=\"#\">Data mining ?</a></li><li class=\"col-md-4\"><a href=\"#\">Machine learning ?</a></li><li class=\"col-md-4\"><a href=\"#\">Scalability ?</a></li><li class=\"col-md-4\"><a href=\"#\">Storage ?</a></li><li class=\"col-md-4\"><a href=\"#\">SQL ?</a></li><li class=\"col-md-4\"><a href=\"#\">NoSQL ?</a></li><li class=\"col-md-4\"><a href=\"#\">Data analysis ?</a></li><li class=\"col-md-4\"><a href=\"#\">Peer-to-Peer ?</a></li><li class=\"col-md-4\"><a href=\"#\">Highly loaded system ?</a></li><li class=\"col-md-4\"><a href=\"#\">Cloud computing ?</a></li><li class=\"col-md-4\"><a href=\"#\">Data compression ?</a></li><li class=\"col-md-4\"><a href=\"#\">Semantics ?</a></li></ul></div>",

	"Computing design ?":"<div class=\"col-md-12 category-services\"><h5>Computing design:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque fugiat quisquam eum, magni, totam natus non officia? Aut reprehenderit, totam commodi ipsum asperiores voluptas autem modi, dolor neque rerum aliquam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere expedita, vel sapiente hic excepturi quia, nobis porro aut earum alias nesciunt, veniam accusantium aperiam unde deserunt dolores architecto maxime numquam.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis error magni, ipsa eos dolorem odit enim, adipisci quae animi a expedita, saepe suscipit provident cumque temporibus aut mollitia ab aperiam.</p><ul><li class=\"col-md-4\"><a href=\"#\">Interface design ?</a></li><li class=\"col-md-4\"><a href=\"#\">Web layout ?</a></li><li class=\"col-md-4\"><a href=\"#\">Design (mobile applications) ?</a></li><li class=\"col-md-4\"><a href=\"#\">Concept art 2D ?</a></li><li class=\"col-md-4\"><a href=\"#\">Drawing characters ?</a></li><li class=\"col-md-4\"><a href=\"#\">Create backgrounds ?</a></li><li class=\"col-md-4\"><a href=\"#\">Рhoto job ?</a></li><li class=\"col-md-4\"><a href=\"#\">Mattle Painting ?</a></li><li class=\"col-md-4\"><a href=\"#\">Create skins ?</a></li><li class=\"col-md-4\"><a href=\"#\">Web design ?</a></li><li class=\"col-md-4\"><a href=\"#\">UI design ?</a></li><li class=\"col-md-4\"><a href=\"#\">Interface design ?</a></li><li class=\"col-md-4\"><a href=\"#\">Work with animation ?</a></li><li class=\"col-md-4\"><a href=\"#\">3D graphics ?</a></li><li class=\"col-md-4\"><a href=\"#\">Vector graphics ?</a></li></ul></div>",

	"Information security ?":"<div class=\"col-md-12 category-services\"><h5>Information security:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem velit tempora, eaque optio facere et omnis totam. Repudiandae error, quia consectetur sunt deleniti, in maxime aperiam sit culpa eos laudantium! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam provident architecto similique laudantium sequi. Veritatis praesentium beatae, alias neque doloribus adipisci, sint voluptas consequatur molestias itaque quam dolorem ipsa! Facere. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure, incidunt! Soluta eveniet commodi minus officiis, quo maiores. Laborum corporis placeat ea assumenda cum, ipsa, necessitatibus fugit, sed veritatis facilis recusandae.</p><ul><li class=\"col-md-4\"><a href=\"#\">External security audit ?</a></li><li class=\"col-md-4\"><a href=\"#\">Internal security audit ?</a></li><li class=\"col-md-4\"><a href=\"#\">The source code audit ?</a></li><li class=\"col-md-4\"><a href=\"#\">Protection against attacks ?</a></li><li class=\"col-md-4\"><a href=\"#\">Cryptographic system ?</a></li><li class=\"col-md-4\"><a href=\"#\">Work with cryptocurrencies ?</a></li><li class=\"col-md-4\"><a href=\"#\">Data encryption ?</a></li><li class=\"col-md-4\"><a href=\"#\">Steganography ?</a></li><li class=\"col-md-4\"><a href=\"#\">Remediation ?</a></li><li class=\"col-md-4\"><a href=\"#\">Cryptanalysis ?</a></li><li class=\"col-md-4\"><a href=\"#\">Digital signature ?</a></li><li class=\"col-md-4\"><a href=\"#\">Anti-spam filters ?</a></li><li class=\"col-md-4\"><a href=\"#\">Captcha ?</a></li><li class=\"col-md-4\"><a href=\"#\">Creation of anonymity ?</a></li></ul></div>",

	"Support sites ?":"<div class=\"col-md-12 category-services\"><h5>Support sites:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi explicabo repellendus beatae enim? Expedita dolor, recusandae excepturi! Mollitia illo praesentium eum optio, ipsam repellendus culpa eaque voluptas neque. Rerum, aliquid! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde ipsum molestiae, dolor facere optio aspernatur deserunt quibusdam? Voluptates dolorem reiciendis autem molestiae corrupti, ratione ab explicabo totam maiores voluptatem magnam.</p><ul><li class=\"col-md-4\"><a href=\"#\">Support sites ?</a></li><li class=\"col-md-4\"><a href=\"#\">Modernization sites ?</a></li><li class=\"col-md-4\"><a href=\"#\">Site administration ?</a></li><li class=\"col-md-4\"><a href=\"#\">Restore sites ?</a></li><li class=\"col-md-4\"><a href=\"#\">Redesign of sites ?</a></li></ul></div>",

	"Computer visionе ?":"<div class=\"col-md-12 category-services\"><h5>Computer visione:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore delectus reiciendis suscipit, incidunt maiores ducimus. Autem dolorem voluptates ea, ex, quibusdam accusantium qui, ab et magnam corporis repudiandae aliquam reiciendis!</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut asperiores fugiat, magnam accusantium ut aliquam dicta magni animi maiores minima eaque tempora consequuntur expedita omnis iure, ad ab eligendi aperiam!</p><ul><li class=\"col-md-4\"><a href=\"#\">Video analysis ?</a></li><li class=\"col-md-4\"><a href=\"#\">Video processing ?</a></li><li class=\"col-md-4\"><a href=\"#\">Image analysis ?</a></li><li class=\"col-md-4\"><a href=\"#\">image processing ?</a></li></ul></div>",

	"System management ?":"<div class=\"col-md-12 category-services\"><h5>System management:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi distinctio dignissimos odit suscipit odio quos debitis illo quas, illum mollitia iure dolores provident et maiores eligendi, doloribus consectetur voluptatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis minima a quaerat quisquam sint cumque, reprehenderit obcaecati nesciunt iusto fuga repudiandae facere, recusandae veniam blanditiis placeat alias ducimus, voluptate quod. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente dolorem est sunt! Voluptatem dicta rem adipisci reiciendis earum delectus laborum, excepturi! Sit, libero numquam, eius iure nisi odio. Eius, nostrum!</p><ul><li class=\"col-md-4\"><a href=\"#\">Virtualization ?</a></li><li class=\"col-md-4\"><a href=\"#\">Server optimization ?</a></li><li class=\"col-md-4\"><a href=\"#\">Mesh-networks ?</a></li><li class=\"col-md-4\"><a href=\"#\">Server administration ?</a></li><li class=\"col-md-4\"><a href=\"#\">Hosting ?</a></li></ul></div>",

	"Translations ?":"<div class=\"col-md-12 category-services\"><h5>Translations:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita eveniet excepturi, nulla iusto voluptatibus a, ut in cumque, sint quasi dolorum, obcaecati delectus veritatis voluptates ab saepe non enim consequuntur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil iste est numquam dicta, debitis ut cumque laboriosam vitae! Eligendi ducimus fugit consequatur ea cum ex atque expedita eius. Recusandae, ipsam?</p><ul><li class=\"col-md-4\"><a href=\"#\">Technical ?</a></li><li class=\"col-md-4\"><a href=\"#\">Medical ?</a></li><li class=\"col-md-4\"><a href=\"#\">Popular science ?</a></li><li class=\"col-md-4\"><a href=\"#\">Hudojestvennye ?</a></li><li class=\"col-md-4\"><a href=\"#\">Advertising translation ?</a></li><li class=\"col-md-4\"><a href=\"#\">Transfers video ?</a></li><li class=\"col-md-4\"><a href=\"#\">Translation audio ?</a></li><li class=\"col-md-4\"><a href=\"#\">Legal translations ?</a></li></ul></div>",

	"Move ?":"<div class=\"col-md-12 category-services\"><h5>Move:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus nihil neque eveniet, officia deserunt quidem cupiditate modi id voluptates laboriosam accusamus minus dignissimos voluptatem, voluptate a exercitationem omnis fuga perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, vero. Quo explicabo id expedita. Quos distinctio quis sunt facere mollitia optio facilis sit labore autem quidem dolores modi ducimus, suscipit.</p><ul><li class=\"col-md-4\"><a href=\"#\">Search promotion ?</a></li><li class=\"col-md-4\"><a href=\"#\">Search engine optimization ?</a></li><li class=\"col-md-4\"><a href=\"#\">Professional copywriting ?</a></li><li class=\"col-md-4\"><a href=\"#\">Site analysis ?</a></li><li class=\"col-md-4\"><a href=\"#\">Market analysis ?</a></li><li class=\"col-md-4\"><a href=\"#\">Advertising on the Internet ?</a></li></ul></div>",

	"Development ?":"<div class=\"col-md-12 category-services\"><h5>Development:</h5><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt impedit magni quisquam corporis odit omnis, incidunt, commodi nesciunt est, dolor ipsum. Eligendi nesciunt repellat laborum odit facere. Quia, consectetur, tempora? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima officiis, est reprehenderit mollitia quod rem! Eius magnam expedita, hic quasi amet rerum ipsam nulla illo voluptas sint nobis vero cum!</p><ul><li class=\"col-md-4\"><a href=\"#\">Creating Web sites ?</a></li><li class=\"col-md-4\"><a href=\"#\">Web portal ?</a></li><li class=\"col-md-4\"><a href=\"#\">Application software ?</a></li><li class=\"col-md-4\"><a href=\"#\">Server software ?</a></li><li class=\"col-md-4\"><a href=\"#\">Mobile applications ?</a></li><li class=\"col-md-4\"><a href=\"#\">Game Development ?</a></li><li class=\"col-md-4\"><a href=\"#\">E-commerce ?</a></li><li class=\"col-md-4\"><a href=\"#\">Geographic services ?</a></li><li class=\"col-md-4\"><a href=\"#\">Highload system ?</a></li><li class=\"col-md-4\"><a href=\"#\">Browser Extension ?</a></li><li class=\"col-md-4\"><a href=\"#\">Client optimization ?</a></li><li class=\"col-md-4\"><a href=\"#\">Data Visualization ?</a></li><li class=\"col-md-4\"><a href=\"#\">Nesting letters ?</a></li><li class=\"col-md-4\"><a href=\"#\">Development IoT ?</a></li></ul></div>"
}